steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/svet-gra-evine:latest', '.']
    
  # 2. Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/svet-gra-evine:latest']
    
  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'svet-gra-evine'
      - '--image'
      - 'gcr.io/$PROJECT_ID/svet-gra-evine:latest'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--update-env-vars'
      - 'APP_REGION=us-west1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '2'

images:
  - 'gcr.io/$PROJECT_ID/svet-gra-evine:latest'

options:
  logging: CLOUD_LOGGING_ONLY
