steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/svet-gradjevine:$COMMIT_SHA', '.']
    
  # 2. Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/svet-gradjevine:$COMMIT_SHA']
    
  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'svet-gradjevine'
      - '--image'
      - 'gcr.io/$PROJECT_ID/svet-gradjevine:$COMMIT_SHA'
      - '--region'
      - 'europe-west3'  # Opciono prilagodi na željeni region (npr. europe-west1)
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/svet-gradjevine:$COMMIT_SHA'
