export const getAuth = () => ({ currentUser: null, onAuthStateChanged: () => () => {} });
export const GoogleAuthProvider = function() {};
export const connectAuthEmulator = () => {};
export const signInWithPopup = () => Promise.reject(new Error('SSR mock'));
export const createUserWithEmailAndPassword = () => Promise.reject(new Error('SSR mock'));
export const signInWithEmailAndPassword = () => Promise.reject(new Error('SSR mock'));
export const sendPasswordResetEmail = () => Promise.resolve();
export const sendEmailVerification = () => Promise.resolve();
export const updateProfile = () => Promise.resolve();
export const onAuthStateChanged = () => () => {};
export const signOut = () => Promise.resolve();
export const onIdTokenChanged = () => () => {};
export const getIdToken = () => Promise.resolve('mock-token');
export const fetchSignInMethodsForEmail = () => Promise.resolve([]);
export const signInWithRedirect = () => Promise.reject(new Error('SSR mock'));
export const getRedirectResult = () => Promise.resolve(null);
