export interface MachineAdData {
  id: string;
  title?: string;
  adTitle?: string;
  name?: string;
  tacnaLokacija?: string;
  location?: string;
  postType?: string;
  status?: string;
  images?: string[];
  logo?: string;
  manufacturer?: string;
  brand?: string;
  adType?: string;
  isPremium?: boolean;
  isUrgent?: boolean;
  modelstr?: string;
  model?: string;
  price?: number | string;
  pricePerDay?: number | string;
  year?: number | string;
  workingHours?: number | string;
  fuelType?: string;
  machFuel?: string;
  powerKw?: number | string;
  viewsCount?: number;
  applicantsCount?: number;
  appCount?: number;
  plotPurpose?: string;
  purpose?: string;
  area?: string | number;
  areaUnit?: string;
  typeLabel?: string;
  collName?: string;
  portfolioImages?: string[];
  references?: string[];
  licenses?: string[];
  certifications?: string[];
  invoiceAvailable?: boolean;
  parkingAvailable?: boolean;
  truckAccess?: boolean;
  haccpCertified?: boolean;
  packagingIncluded?: boolean;
  dailyCapacityMeals?: number;
  createdAt?: any;
  expiresAt?: any;
}
